# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Rujax.LateNight
PackageVersion: 0.0.1
PackageLocale: en-US
Publisher: Rujax
PublisherUrl: https://github.com/rujax/late-night
PublisherSupportUrl: https://github.com/rujax/late-night/issues
Author: Rujax
PackageName: LateNight
PackageUrl: https://github.com/rujax/late-night
License: GPL-3.0
LicenseUrl: https://github.com/rujax/late-night/blob/main/LICENSE
Copyright: Copyright (C) 2026 Rujax. All rights reserved.
CopyrightUrl: https://github.com/rujax/late-night/blob/main/LICENSE
ShortDescription: An app that can automatically execute tasks at late night.
Description: An app that can automatically execute tasks at late night.
Moniker: latenight
Tags:
- system
- theme
- volume
- shutdown
- utility
ReleaseNotes: '- Automatically switch system dark/light mode\n- Automatically lower/increase system volume'
ReleaseNotesUrl: https://github.com/rujax/late-night/releases/tag/v0.0.1
ManifestType: defaultLocale
ManifestVersion: 1.12.0
